from __future__ import annotations

import re
import shutil
from pathlib import Path
from typing import Any

DOC_TYPES = {"prd", "spec"}


def init_source_package_from_document(
    *,
    repo_root: Path,
    project_name: str,
    doc_type: str,
    source_path: str,
    target_root: Path | None = None,
) -> dict[str, Any]:
    normalized_doc_type = doc_type.lower().lstrip("-")
    if normalized_doc_type not in DOC_TYPES:
        raise ValueError("doc_type must be `prd` or `spec`")
    _validate_project_name(project_name)

    source = _resolve_source(repo_root, source_path)
    title = _extract_title(source)
    slug = _slugify(title) or _slugify(source.stem) or "feature"
    specs_root = (
        (target_root.resolve() / "specs")
        if target_root
        else repo_root / "apps" / project_name / "specs"
    )
    feature_dir = specs_root / f"{_next_feature_number(specs_root):03d}-{slug}"
    feature_dir.mkdir(parents=True, exist_ok=False)

    imported_name = "source-prd.md" if normalized_doc_type == "prd" else "source-spec.md"
    destination = feature_dir / imported_name
    shutil.copyfile(source, destination)
    source_manifest = feature_dir / "source-package.json"
    source_manifest.write_text(
        _source_manifest_json(
            title=title,
            doc_type=normalized_doc_type,
            source_path=source,
            imported_path=destination,
        ),
        encoding="utf-8",
    )

    return {
        "project_name": project_name,
        "doc_type": normalized_doc_type,
        "feature_dir": _output_path(repo_root, feature_dir, absolute=target_root is not None),
        "source_path": str(source),
        "imported_path": _output_path(repo_root, destination, absolute=target_root is not None),
        "source_package_path": _output_path(
            repo_root,
            source_manifest,
            absolute=target_root is not None,
        ),
        "generated_seed_artifacts": [],
        "expected_artifacts": _expected_artifacts(normalized_doc_type),
    }


def _validate_project_name(project_name: str) -> None:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]*", project_name):
        raise ValueError("project_name 只能包含字母、数字、下划线和中划线，且不能以符号开头")


def _resolve_source(repo_root: Path, source_path: str) -> Path:
    source = Path(source_path)
    if not source.is_absolute():
        source = repo_root / source
    source = source.resolve()
    if not source.exists() or not source.is_file():
        raise ValueError(f"source document not found: {source}")
    return source


def _extract_title(source: Path) -> str:
    text = source.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            stripped = stripped.lstrip("#").strip()
        return stripped or source.stem
    return source.stem


def _slugify(value: str) -> str:
    tokens = re.findall(r"[a-z0-9]+", value.lower())
    return "-".join(tokens[:6])


def _next_feature_number(specs_root: Path) -> int:
    max_number = 0
    if specs_root.exists():
        for child in specs_root.iterdir():
            if child.is_dir():
                match = re.match(r"^(\d{3})-", child.name)
                if match:
                    max_number = max(max_number, int(match.group(1)))
    return max_number + 1


def _relative_to_repo(repo_root: Path, path: Path) -> str:
    return path.resolve().relative_to(repo_root.resolve()).as_posix()


def _output_path(repo_root: Path, path: Path, *, absolute: bool) -> str:
    if absolute:
        return str(path.resolve())
    return _relative_to_repo(repo_root, path)


def _source_manifest_json(
    *,
    title: str,
    doc_type: str,
    source_path: Path,
    imported_path: Path,
) -> str:
    import json

    payload = {
        "schema": "agentic-source-package/v1",
        "title": title,
        "doc_type": doc_type,
        "source_path": str(source_path),
        "imported_path": str(imported_path),
        "seed_artifacts_created": [],
        "notes": [
            "Raw source is archived only.",
            "Product state, implementation plan, and task graph are generated by workflow nodes.",
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _expected_artifacts(doc_type: str) -> list[str]:
    if doc_type == "prd":
        return [
            "product-prd.md",
            "product-contract.json",
            "stories.json",
            "production-spec.md",
            "tasks.json",
            "task-graph.json",
        ]
    return [
        "product-contract.json",
        "stories.json",
        "production-spec.md",
        "tasks.json",
        "task-graph.json",
    ]
